//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionData
{
    using System;
    
    public enum UserRoles : long
    {
        User = 10,
        PowerUser = 20,
        Admin = 30
    }
}
